### ISSUE TITLE
[-> 1 2 3]

### ISSUE THREAD

**Issue by Sgeo** [takikawa/racket-clojure#1]
I'm not that familiar with Racket, although it's my current language-of-obsession, but as far as I understand #%app is only used for function applications, yet you're using it to try to find all [] and {} usage. If a [] or {} form starts with a macro, I don't think #%app will be placed there, and thus, instead of erroring about being unable to take the value of a macro, the macro will be executed at that point. I may be wrong, I haven't actually tested it myself.

**Comment by AlexKnauth** [comment]
Does this look good to you?
